### ISSUE TITLE
[FEAT ✨] Improve README per https://github.com/mrousavy/react-native-vision-camera/issues/3212

### ISSUE THREAD

**Issue by ChristopherGabba** [luicfrr/react-native-vision-camera-face-detector#103]
Referencing issue here:
https://github.com/mrousavy/react-native-vision-camera/issues/3212 

I think the README could be a little clearer for the issue referenced above:
1. Emphasize the importance of your recommended method over the RNVC approach because it solves the issue above
2. Update the React-Native-Vision-Camera example in the README to show the `runAsync()` approach or whatever you are doing under the hood in the `Camera` component in your library.

I followed the docs directly from the section here:
<img width="454" alt="Screenshot 2024-10-08 at 1 25 26 PM" src="https://github.com/user-attachments/assets/45487023-bc54-4569-a8ba-0070ee162683">

And it resulted in the issue above. I also think a link to the docs about `runAsync` could be mentioned: https://react-native-vision-camera.com/docs/guides/frame-processors-interacting#running-asynchronously

Thanks for this awesome package!

**Comment by luicfrr** [comment]
Thanks 👍🏼
