### ISSUE TITLE
[BUG 🐛] minFaceSize provided causing android app crash

### ISSUE THREAD

**Issue by barnettet31** [luicfrr/react-native-vision-camera-face-detector#105]
**Describe the bug:**
Updated my app to the latest version recently. Ran a release build on android and kept getting an exception when the camera was made active in the view that was causing the app to crash on android. (see error). Problem does not happen on ios. 

I believe the issue is happening here: 

![location](https://github.com/user-attachments/assets/c8028352-93e2-4633-a5de-ebdec9449f66)

**Minimum reproducible example:**
Start existi

**Expected behavior:**

**I have tried:**
I had to fiddle with the options for minFaceSize, if I provided any decimal value (Example 0.01) then the application would crash. If I provided a whole number it would also crash. 
![options](https://github.com/user-attachments/assets/28272325-4e1e-4464-b2cc-d1b6424d00c7)

**Logs and Screenshots**
Error in Android Studio. I don't really work with Kotlin, but might be able to cast as a double then convert to a float? 
![error](https://github.com/user-attachments/assets/b43f139d-c680-43fd-a555-013516413eeb)

**Device:**
 - Device: Galaxy s23 ultra & galaxy s9
 - OS: Android

**`package.json` file:**
{
   "dependencies": {
    "expo": "51.0.38"
     "react-native-vision-camera": "4.5.0",
     "react-native-vision-camera-face-detector": "1.7.1",
     "react-native-worklets-core": "1.3.3"
  }
}

**Comment by luicfrr** [comment]
@barnettet31 can you please check if 6fa700a really fix this issue?

**Comment by barnettet31** [comment]
I checked and it seems to have fixed the bug, apologies I had to go head down on a project at work and didn't get out of the office much haha
