### ISSUE TITLE
[FEAT ✨] Cross-compatability with react-native-webrtc

### ISSUE THREAD

**Issue by XChikuX** [luicfrr/react-native-vision-camera-face-detector#112]
**Is your feature request related to a problem? Please describe.**

Currently react-native-webrtc uses its own camera. This becomes a problem because the useful features of frame_processors is not felt in the video sent across. 

**Describe the solution you'd like**
I want to be able to send frames to and from webrtc clients. 

Please forgive me if this is beyond this project. Just wanted to assess scope :)

**Additional context**
There is also an issue where the package minSdk isn't satisfied due to compatibility [problems](https://github.com/react-native-webrtc/react-native-webrtc/issues/1646)

**Comment by luicfrr** [comment]
The only purpose of this package is to detect faces on a frame.
Other frame manipulations are not planned.
I'll not work on it unless you pay me for that.
