### ISSUE TITLE
[BUG 🐛] Facing error in android - Execution error

### ISSUE THREAD

**Issue by Tarun24RN** [luicfrr/react-native-vision-camera-face-detector#113]
Facing error in android - Execution error: {};

const device =  useCameraDevice('front')

function handleFacesDetection(
        faces: Face[],
        frame: Frame
      ) { 
        try {
          if(faces.length){
            setlandmarksData(faces)
        }
        } catch (error) {
          ShowLogs("error",error)
        }
       
      }

 const faceDetectionOptions = {
        performanceMode: 'accurate',
        landmarkMode: 'all'
    }

{!!device? <Camera
        ref={cameraRef}
          style={StyleSheet.absoluteFill}
          device={device}
          photo={true}
          isActive={true}
          faceDetectionCallback={ handleFacesDetection }
          faceDetectionOptions={ faceDetectionOptions }
        /> : <Text>
          No Device
        </Text>}
        
        "react-native-vision-camera": "^4.5.3",
    "react-native-vision-camera-face-detector": "^1.7.1",
    "react-native-worklets-core": "^1.3.3",
"react-native": "0.75.4",

**Comment by luicfrr** [comment]
No logs provided, bad code formatting.... its really hard to help you this way.
Closing issue.
