### ISSUE TITLE
Original 'Frame'

### ISSUE THREAD

**Issue by YuriOlepir** [luicfrr/react-native-vision-camera-face-detector#14]
Hi, is it possible to get the original 'frame: Frame' from the frameProcessor?

**Comment by nonam4** [comment]
Wich method are you using? Recommended or default?

**Comment by YuriOlepir** [comment]
> Wich method are you using? Recommended or default?
I'm using your method 'faceDetectionCallback'. The native 'frameProcessor' method is not working because it's resigned by 'cameraFrameProcessor' inside your Camera component. 

I'm working on the simple ID scanning, so I need to track face and text, that's why I need the original Frame. 
I made small changes inside your `detectFaces` function, so now I have the original Frame. 
it would be good to include this in your next releases.

node_modules/react-native-vision-camera-face-detector/src/FaceDetector.ts

`export function detectFaces(
  frame: Frame,
  callback: CallbackType,
  options?: FaceDetectionOptions
) {
  'worklet'
  if ( plugin == null ) {
    throw new Error( 'Failed to load Frame Processor Plugin "detectFaces"!' )
  }

  // @ts-ignore
  const result = {...plugin.call( frame, options ), originalFrame: frame} as DetectionResult
  callback( result )
}
`

**Comment by nonam4** [comment]
@YuriOlepir sure, I’ll add this feat in next release. 

In some of my tests I had a problem on ios (also there’s an open issue on vision camera about this). In my case the whole camera freeze after a few frame processor call but this happens only if I try to access original frame data. 

Please let me know if this happens to you too.
