### ISSUE TITLE
IOS : installation error CocoaPods could not find compatible versions for pod "VisionCameraFaceDetector"

### ISSUE THREAD

**Issue by primesay** [luicfrr/react-native-vision-camera-face-detector#4]
after adding 
`yarn add react-native-vision-camera-face-detector`

i got this error : 
`[!] CocoaPods could not find compatible versions for pod "VisionCameraFaceDetector":
  In Podfile:
    VisionCameraFaceDetector (from `../node_modules/react-native-vision-camera-face-detector`)`

ENV
` 
"react-native-vision-camera": "^3.9.0",
 "react-native-worklets-core": "^0.3.0",
"react-native": "0.72.3",
`

any help ?

**Comment by nonam4** [comment]
Hello, are you using `expo` in your project? 
If you do: change `deploymentTarget` version inside `app.config.js` or `app.json` to (at least) 13.4 (I recomend using 14.0).
If you don't: check `platform :ios` version inside `Podfile` and adjust it to above versions.

Also, have you tryed removing `Podfile.lock` and running `pod install` or `pod install --repo-update` or `pod repo update`.
You can also try [these](https://stackoverflow.com/a/48657622/9894625) steps.

Please give me a feedback about it

**Comment by tarikdev1** [comment]
i don't use expo,  
the solution was to update the min IOS version to 13.4


thanks
