### ISSUE TITLE
react-native-vision-camera-face-detector:compileDebugKotlin

### ISSUE THREAD

**Issue by SantoshYadavSridix** [luicfrr/react-native-vision-camera-face-detector#50]
**Describe the bug**
* What went wrong:
Execution failed for task ':react-native-vision-camera-face-detector:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

**Expected behavior**
App need to run using npm run android.

**Logs and Screenshots**
![Screenshot 2024-04-29 at 6 32 20 PM](https://github.com/nonam4/react-native-vision-camera-face-detector/assets/166494571/885d6880-cb01-4054-bfad-2d86aac9c86b)

**Smartphone (please complete the following information):**
 - Device: [e.g. Android 11]
 - Vision Camera version [e.g. 4.0.0-beta.11]
 - Face detector version [e.g. 1.6.1]
 - react-native-worklets-core: 0.4.0

**Additional context**
"react": "18.2.0",
"react-native": "0.73.7", // also tried in 0.71.11

Also Tried 
`buildscript {
    ext {
    ...
        kotlinVersion = "1.9.0"
    }
    dependencies {
    ...
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion")
    }
}`
 in android/build.gradle

**Comment by SantoshYadavSridix** [comment]
Also tried kotlinVersion = "1.8.0"

**Comment by SantoshYadavSridix** [comment]
I have tried with deleting node_modules and package-lock.json. But now new issue comes up it is react native vision camera.
```
/Users/sridix/Library/Android/sdk/cmake/3.22.1/bin/ninja \
        -C \
        "node_modules/react-native-vision-camera/android/.cxx/Debug/2n4l1ga6/arm64-v8a" \
        VisionCamera
    from node_modules/react-native-vision-camera/android
```

Now, i don't have time to wait for other response. So, i need to go for native modules.

```
Note: There are some more changes in order to resolve this issue (react-native-vision-camera-face-detector:compileDebugKotlin)
File Location:- node_modules/react-native-vision-camera-face-detector/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.kt
import com.mrousavy.camera.core.types.Orientation
import com.mrousavy.camera.frameprocessors.Frame
import com.mrousavy.camera.frameprocessors.FrameProcessorPlugin
import com.mrousavy.camera.frameprocessors.VisionCameraProxy
```
Need to add core and frameprocessors(instead of frameprocessor).

**Comment by nonam4** [comment]
> ```
> Note: There are some more changes in order to resolve this issue (react-native-vision-camera-face-detector:compileDebugKotlin)
> File Location:- node_modules/react-native-vision-camera-face-detector/android/src/main/java/com/visioncamerafacedetector/VisionCameraFaceDetectorPlugin.kt
> import com.mrousavy.camera.core.types.Orientation
> import com.mrousavy.camera.frameprocessors.Frame
> import com.mrousavy.camera.frameprocessors.FrameProcessorPlugin
> import com.mrousavy.camera.frameprocessors.VisionCameraProxy
> ```
> 
> Need to add core and frameprocessors(instead of frameprocessor).

This error is happening because you're messing up with this package version and dependencies versions.

Read `1.6.1` release notes and also double check if you have done [this](https://github.com/nonam4/react-native-vision-camera-face-detector/issues/49#issuecomment-2082793196) comment's sollution.
