### ISSUE TITLE
How do I use image path instead of frame object?

### ISSUE THREAD

**Issue by MuazzezA** [luicfrr/react-native-vision-camera-face-detector#58]
I know this package works with vision-camera. But can't I perform facial recognition with just the image? Because there should be a section where I can only use images.
I load the image file with react-native-image-picker (launchImageLibrary).

If I can convert the image data into a frame object, will it be useful? help please.

  "react-native-image-picker": "^7.1.0",
  "react-native-vision-camera": "^3.9.2",
  "react-native-vision-camera-face-detector": "^1.6.3",
  "react-native-worklets-core": "^1.0.0",

**Comment by luicfrr** [comment]
This is not a feature I'm planning to implement unless you want to pay me for that.
