### ISSUE TITLE
[BUG 🐛] CMake Error in CMakeLists.txt Imported target "react-native-worklets-core::rnworklets" includes non-existent path

### ISSUE THREAD

**Issue by MuazzezA** [luicfrr/react-native-vision-camera-face-detector#59]
**Issue**

<img width="1078" alt="Screenshot " src="https://github.com/luicfrr/react-native-vision-camera-face-detector/assets/64336826/f6d03d64-7828-4d8c-add4-6a5d8b2f9091">

This error does not occur until I add the react-native-vision-camera-face-detector package.

**Device:**
 - Device: emulator
 - OS: android

**`package.json` file:**

{
   "dependencies": {
    "react-native-vision-camera": "^3.9.2",
    "react-native-vision-camera-face-detector": "^1.6.3",
    "react-native-worklets-core": "^1.0.0",
  }
}

**Comment by luicfrr** [comment]
You’re not using same tested vision-camera neither worklets-core versions.

**Comment by luicfrr** [comment]
Please make sure you’re using the same testes versions before opening issues or you’ll be blocked.
