### ISSUE TITLE
[BUG 🐛] [Android] faceDetectionCallback not detecting face on release mode

### ISSUE THREAD

**Issue by mangjuned** [luicfrr/react-native-vision-camera-face-detector#65]
**Describe the bug:**
My previous version is
```
"react-native-vision-camera": "^4.0.0-beta.13",
"react-native-vision-camera-face-detector": "^1.4.0",
"react-native-worklets-core": "^0.4.0",
```
it's work fine in debug and release mode, but after updating to
```
"react-native-vision-camera": "^4.0.5",
"react-native-vision-camera-face-detector": "^1.6.3",
"react-native-worklets-core": "^1.3.3",
```
faceDetectionCallback not detecting face on release mode, but it's works fine in debug mode.

**I have tryed:**
clean cache

**Device:**
 - Device: Redmi note 13 pro 5g 
 - OS: android 13 

**`package.json` file:**
```
{
   "dependencies": {
    "react-native-vision-camera": "^4.0.5",
    "react-native-vision-camera-face-detector": "^1.6.3",
    "react-native-worklets-core": "^1.3.3",
  }
}
```

**Comment by luicfrr** [comment]
I have not tested face-detector on vision-camera `4.0.5`. 
I can't say if it's really working on this version.

**Comment by ibrahim-developes** [comment]
Doesnot work even on the version given in README

 "react-native-vision-camera": "4.0.4",
    "react-native-vision-camera-face-detector": "^1.6.3",
    "react-native-worklets-core": "1.3.3",

**Comment by bonnmh** [comment]
Has anyone fixed their problem yet?
