### ISSUE TITLE
[BUG 🐛] IOS not working

### ISSUE THREAD

**Issue by w3Enzo** [luicfrr/react-native-vision-camera-face-detector#66]
I'm developing an ios using react-native and the app turns off when I turn on face-detector in the ios after applying the example code

  "react-native": "0.73.5"
   "react-native-vision-camera": "~4.0.5"
    "react-native-vision-camera-face-detector": "^1.6.3"
   "react-native-worklets-core": "^1.3.3"
   "react-native-reanimated": "3.8.0"

IOS version 14.0

help me

---- 
I checked the error in xcode and it is a memory issue

**Comment by luicfrr** [comment]
without logs nor minimum example code I can't help you.

**Comment by w3Enzo** [comment]
Running face-detector in an ios environment turns off the app and won't be able to upload logs. The code used the example code on the git page
