### ISSUE TITLE
[BUG 🐛] Detected face wrong orientation on Samsung A14

### ISSUE THREAD

**Issue by edritech93** [luicfrr/react-native-vision-camera-face-detector#69]
wrong orientation when detected face

**Device:**
 - Device: Samsumg A14
 - OS: Android

**`package.json` file:**
```
{
...
   "dependencies": {
     "react-native-vision-camera": "4.1.0",
     "react-native-vision-camera-face-detector": "^1.6.3",
     "react-native-worklets-core": "^1.3.3"
  }
...
}
```

**Comment by luicfrr** [comment]
@Aycom366 I'm really busy on another project these month, I didn't have time to even check new vision-camera releases.

If you need an urgent patch maybe you should considerate on paying me for that then I'll work on it on my free/rest time.
If you don't want to pay me for this then you can work on a fix yourself or you'll need to wait for a fix (yes, I'll keep this package updated).

**Comment by luicfrr** [comment]
@edritech93 I just released 1.7.0 version.
Can you please check if it fix this issue?

**Comment by luicfrr** [comment]
Closing this issue for now.
If the error persists maybe we can reopen it.

**Comment by frodriguez-hu** [comment]
@luicfrr Question, have you tried this to get the orientation? Suggested by Google

```
private val ORIENTATIONS = SparseIntArray()

init {
    ORIENTATIONS.append(Surface.ROTATION_0, 0)
    ORIENTATIONS.append(Surface.ROTATION_90, 90)
    ORIENTATIONS.append(Surface.ROTATION_180, 180)
    ORIENTATIONS.append(Surface.ROTATION_270, 270)
}

/**
 * Get the angle by which an image must be rotated given the device's current
 * orientation.
 */
@RequiresApi(api = Build.VERSION_CODES.LOLLIPOP)
@Throws(CameraAccessException::class)
private fun getRotationCompensation(cameraId: String, activity: Activity, isFrontFacing: Boolean): Int {
    // Get the device's current rotation relative to its "native" orientation.
    // Then, from the ORIENTATIONS table, look up the angle the image must be
    // rotated to compensate for the device's rotation.
    val deviceRotation = activity.windowManager.defaultDisplay.rotation
    var rotationCompensation = ORIENTATIONS.get(deviceRotation)

    // Get the device's sensor orientation.
    val cameraManager = activity.getSystemService(CAMERA_SERVICE) as CameraManager
    val sensorOrientation = cameraManager
            .getCameraCharacteristics(cameraId)
            .get(CameraCharacteristics.SENSOR_ORIENTATION)!!

    if (isFrontFacing) {
        rotationCompensation = (sensorOrientation + rotationCompensation) % 360
    } else { // back-facing
        rotationCompensation = (sensorOrientation - rotationCompensation + 360) % 360
    }
    return rotationCompensation
}
```

Cause for last vision camera version on my last test and with the last version of this library, it wasn't working properly either

**Comment by luicfrr** [comment]
@frodriguez-hu I didn't tested it this way on kotlin.
I saw some code using `activity.windowManager` when I was using java some time ago but I couldn't have access to current activity neither windowManager.

Anyway, I'll test this now on kotlin and give you credits if it works.

If you already have this working on your device and want to create a PR I'll apretiate a lot.

**Comment by frodriguez-hu** [comment]
@luicfrr I do not have it working cause I wasn't able to implement it correctly, I can't mount the android project on android studio and when I want to start it with the changes I am not able to do it.
I send the cameraId from `device.id` from the javascript side and then sending it to the plugin config. Then I had errors trying to get the activity from the ReactPackage, but I think that is cause I wasn't able to set up Kotlin properly so Android Studio is not showing me the errors on the code. 

I am not completely sure, I tried it again on a new project and it worked fine, but it is not working on my main project, I don't know it it could have conflicts with another dependency line reanimated maybe? I don't know, but is quite weird

**Comment by frodriguez-hu** [comment]
@luicfrr If I hardcode the rotation to 270 degrees it work properly, but it stop working on landscape and other orientations. 

And setting this condition to be always true

`if (rotation == 270 || rotation == 90) {` 

What would happen on other devices? All android devices start with an orientation of 90 degrees?

**Comment by luicfrr** [comment]
@frodriguez-hu where are you hardcoding this `if(rotation ....)`?
In my latest version there's no ifs in rotation.

And yes, in every device (android and ios), camera orientation is always -90deg rotated

**Comment by frodriguez-hu** [comment]
@luicfrr Sorry! I am using `1.4.0` version (We have an older react native version (0.71.12) and we are limited to 3.x.x on VC). But on a test i did on the last version it wasn't catching any face either. 
Let me know if you implement the other suggestion, or I will try to implement it too, how do you prepare the project on Android Studio? I'd like to help maintaining this since we are probably using it on a production app

**Comment by luicfrr** [comment]
@frodriguez-hu let's keep this conversation going on [this](https://github.com/luicfrr/react-native-vision-camera-face-detector/discussions/77) discussion.
