### ISSUE TITLE
[BUG 🐛] Wrong orientation on Android device

### ISSUE THREAD

**Issue by tienbui2408** [luicfrr/react-native-vision-camera-face-detector#70]
I detect when android phone in portrait mode always returns []. I have tried many ways to upgrade the library as well as follow the instructions but all failed. If there is any way to fix the error please help me!!!

<img width="136" alt="image" src="https://github.com/luicfrr/react-native-vision-camera-face-detector/assets/127682806/f97cb4a4-d2b0-41e9-a50d-3765b94f6bb5">

**Device:**
 - Device:  Xiaomi Redmi Note9s
 - OS:  Android 10

**`package.json` file:**

   "dependencies": {
    "react-native-vision-camera": "^4.2.1",
    "react-native-vision-camera-face-detector": "^1.6.3",
    "react-native-worklets-core": "^1.3.3",
  }

**Comment by Aycom366** [comment]
have you found a workaround for this? @tienbui2408
