### ISSUE TITLE
[BUG 🐛] App crash while using useFrameProcessor 

### ISSUE THREAD

**Issue by OmarKhelifi** [luicfrr/react-native-vision-camera-face-detector#78]
**Describe the bug:**
I try the example code, but My app is crashing when I'm trying to enable FrameProcessor. The app works fine without FrameProcessor.

**Minimum reproducible example:**

```
/* eslint-disable prettier/prettier */
import React, {useEffect, useRef} from 'react';
import {View, StyleSheet, Text, Alert} from 'react-native';
import {
  Camera,
  useCameraDevice,
  useCameraPermission,
  useFrameProcessor,
} from 'react-native-vision-camera';
import {useFaceDetector} from 'react-native-vision-camera-face-detector';
import {Worklets} from 'react-native-worklets-core';


const CameraPage = () => {
  const device = useCameraDevice('front');
  const {hasPermission, requestPermission} = useCameraPermission();

  useEffect(() => {
    (async () => {
      if (hasPermission === 'not-determined') {
        const status = await requestPermission();
        if (status === 'denied' || status === 'restricted') {
          Alert.alert(
            'Permission denied',
            'Camera access is restricted. Please enable it in the device settings.',
          );
        }
        console.log({status});
      }
    })();
  }, [hasPermission, requestPermission]);

  const faceDetectionOptions = useRef({
    // detection options
  }).current;

  useEffect(() => {
    (async () => {
      const status = await Camera.requestCameraPermission();
      console.log({status});
    })();
  }, [device]);

  const {detectFaces} = useFaceDetector(faceDetectionOptions);

  const handleDetectedFaces = Worklets.createRunOnJS(faces => {
    console.log('faces detected', faces);
  });

  const frameProcessor = useFrameProcessor(
    frame => {
      'worklet';
      const faces = detectFaces(frame);
      // ... chain frame processors
      // ... do something with frame
      handleDetectedFaces(faces);
    },
    [handleDetectedFaces],
  );
  if (device == null) {
    return (
      <View style={styles.container}>
        <Text>No Camera</Text>
      </View>
    );
  }

  if (!hasPermission) {
    return (
      <View style={styles.container}>
        <Text>Camera is not authorized</Text>
      </View>
    );
  }

  console.log('CameraPage');

  return (
    <View style={styles.container}>
      <Camera
        style={StyleSheet.absoluteFill}
        device={device}
        isActive={true}
        frameProcessor={frameProcessor}
      />
    </View>
  );
};

export default CameraPage;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loading: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'black',
  },
});

```

**Logs and Screenshots**

```
There is no error logged.
```
 

**Device:**
 - Device: Samsung A52

**`package.json` file:**

{
   "dependencies": {
     "react-native": "0.74.3",
     "react-native-vision-camera": "4.4.1",
     "react-native-vision-camera-face-detector": "^1.7.0",
     "react-native-worklets-core": "^1.3.3"
     "react-native-reanimated": "3.12.1",
     "expo": "^51.0.17",
  }
}

**Min O.S version:**
- Android: SDK 26 (Android 8)

**Comment by luicfrr** [comment]
Please provide native logs so I can try to help you.

**Comment by OmarKhelifi** [comment]
problem cache

**Comment by IlyaZusko** [comment]
> problem cache

I'm facing a similar problem. Could you clarify what the problem was and how you fixed it, please?

**Comment by IlyaZusko** [comment]
> > problem cache
> 
> I'm facing a similar problem. Could you clarify what the problem was and how you fixed it, please?
> 
> In my case, after the application crashes, xcode displays errors like: "Thread 68: EXC_BAD_ACCESS (code=2, address=0x16c9cbf40)"

I tried to clean the cache before building the application, all the libraries in my project correspond to those described above. I think I'm at a dead end and I really need your help @luicfrr @OmarKhelifi

**Comment by Saqib92** [comment]
> > > problem cache
> > 
> > 
> > I'm facing a similar problem. Could you clarify what the problem was and how you fixed it, please?
> > In my case, after the application crashes, xcode displays errors like: "Thread 68: EXC_BAD_ACCESS (code=2, address=0x16c9cbf40)"
> 
> I tried to clean the cache before building the application, all the libraries in my project correspond to those described above. I think I'm at a dead end and I really need your help [@luicfrr](https://github.com/luicfrr) [@OmarKhelifi](https://github.com/OmarKhelifi)

Same issue.
