### ISSUE TITLE
[BUG 🐛] Worklets.createRunOnJS stop the app

### ISSUE THREAD

**Issue by IlyaZusko** [luicfrr/react-native-vision-camera-face-detector#80]
In my project, I use the frameProcessor from the react-native-vision-camera library. I have a code like this:
```
  const device = useCameraDevice('front');

  const {detectFaces} = useFaceDetector({
    classificationMode: 'all',
  });

  const handleDetectedFaces = Worklets.createRunOnJS(faces => {
    console.log('faces detected', faces);
  });

  const frameProcessor = useFrameProcessor(
    frame => {
      'worklet';
      const faces = detectFaces(frame);
      handleDetectedFaces(faces);
    },
    [],
  );

  return (
    <View style={{ flex: 1 }}>
      <Camera
        style={StyleSheet.absoluteFill}
        device={device}
        isActive={true}
        enableFpsGraph
        fps={15}
        videoHdr={false}
        frameProcessor={frameProcessor}
      />
    </View>
    )
```
When I launch the project and go to the screen where the function is called, the application immediately freezes and in xcode I get errors like in the screenshot below
<img width="1440" alt="Снимок экрана 2024-07-11 в 12 22 34" src="https://github.com/margelo/react-native-worklets-core/assets/115986339/fb1f8d1f-7ed0-4fab-b615-5379d621f37b">

**My package.json**
```
"react": "^18.3.1",
"react-native": "^0.74.3",
"react-native-vision-camera": "^4.4.1",
"react-native-vision-camera-face-detector": "^1.7.0",
"react-native-worklets-core": "^1.3.3",
```

**My babel.config.js**
```
module.exports = {
  presets: ['module:@react-native/babel-preset', 'module:react-native-dotenv'],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        processNestedWorklets: true,
      },
    ],
    ['react-native-worklets-core/plugin'],
  ],
};
```

Initially, I assumed that this was due to the fact that I transfer too often from the worklet stream to the js stream, however, I also tried to write just a functional where, at the click of a button, I would transfer information to the js stream once and the application still hung with the same errors in xcode. Has anyone faced similar problems and how did you solve them?

**Device:**
 - Device: Iphone 15
 - OS: 18.0

**Comment by mickytroxxy** [comment]
Facing the same issue too, @IlyaZusko did you find a fix for this?

**Comment by IlyaZusko** [comment]
> Facing the same issue too, @IlyaZusko did you find a fix for this?

It seems that this guide was the solution for me:
https://github.com/reactwg/react-native-new-architecture/blob/main/docs/enable-apps.md
