### ISSUE TITLE
Face detection Issue in different device orientaion and preview orientation

### ISSUE THREAD

**Issue by sjaiswalgit** [luicfrr/react-native-vision-camera-face-detector#93]
Currently this plugin does not respond to device orientation change and preview orientation change, and thus detection is not proper if device is holded in different orientation other than potrait (max rollAngle for detection goes up to 100deg ) . Need feature like passing arguments with frame which accounts for angle rotation

**Comment by luicfrr** [comment]
without reproducible code I can't help
