### ISSUE TITLE
[BUG 🐛] How to convert the frame to image?

### ISSUE THREAD

**Issue by levepic** [luicfrr/react-native-vision-camera-face-detector#94]
I tried everything to simply capture a frame as an image but frame.toArrayBuffer() silently fails as everything else. It should be pretty easy and straightforward, what else you would do with the frame? Usecase: doring the video you take screens of the user performing tasks and you also record the whole on video. Hence you need a record and meanwhile to take photos (frames) when the user performed the actions (smile, etc), so its easy to check later. Am i missing somehting? Also checked vision camera docs but nothing works.

**Comment by luicfrr** [comment]
You should search this into `vision-camera` docs

**Comment by levepic** [comment]
Found out you can still take snapshot while recording if you dont need the full frame
